INSERT INTO recipes (user_id, title, description, ingredients, instructions, category, image_url)
VALUES 
(1, 'Paneer Butter Masala', 'A rich, creamy curry made with paneer and a spiced tomato gravy.', 'Paneer, Butter, Tomatoes, Cream, Onion, Garlic, Ginger, Garam Masala, Kasuri Methi, Red Chili Powder', 'Sauté onions, garlic, and ginger in butter, add tomato puree and spices, cook until the gravy thickens. Add paneer cubes and simmer with cream. Garnish with kasuri methi and serve hot.', 'Main Course', 'https://myfoodstory.com/wp-content/uploads/2021/07/restaurant-style-paneer-butter-masala-2-500x500.jpg'),
(1, 'Chicken Biryani', 'A fragrant rice dish made with marinated chicken, aromatic spices, and basmati rice.', 'Chicken, Basmati Rice, Yogurt, Onion, Tomato, Garlic, Ginger, Garam Masala, Saffron, Ghee, Mint', 'Marinate chicken with yogurt and spices. Layer with partially cooked rice and cook on low heat (Dum) until the chicken is tender. Garnish with mint and fried onions.', 'Main Course', 'https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Chicken-Biryani-Recipe.jpg'),
(1, 'Aloo Gobi', 'A simple dry curry made with potatoes (Aloo) and cauliflower (Gobi).', 'Potatoes, Cauliflower, Onion, Tomatoes, Garlic, Ginger, Turmeric, Cumin, Coriander Powder, Garam Masala', 'Sauté onions, garlic, and ginger, then add potatoes and cauliflower along with spices. Cook until tender and serve with roti or rice.', 'Vegetarian', 'https://niksharmacooks.com/wp-content/uploads/2022/11/AlooGobiDSC_5234.jpg'),
(1, 'Masoor Dal', 'A hearty red lentil curry made with Indian spices.', 'Masoor Dal (Red Lentils), Onion, Tomatoes, Garlic, Ginger, Cumin Seeds, Turmeric, Coriander Powder, Garam Masala, Ghee', 'Cook lentils with turmeric until soft. Prepare a tadka with ghee, cumin, garlic, and spices. Add the tadka to the dal and simmer. Serve hot.', 'Vegan, Main Course', 'https://media.istockphoto.com/id/1130228942/photo/indian-dal-traditional-indian-soup-lentils-indian-dhal-spicy-curry-in-bowl-spices-herbs.jpg?s=612x612&w=0&k=20&c=ciPGZR4hkLeUL-nRxY4iAh539zYLgUkNz82GG_nJG5A='),
(1, 'Samosa', 'A crispy, deep-fried pastry filled with spiced potatoes and peas.', 'Potatoes, Green Peas, Onions, Ginger, Cumin Seeds, Garam Masala, Salt, Flour (for dough), Oil (for frying)', 'Prepare the filling by sautéing potatoes and peas with spices. Roll the dough, shape into triangles, stuff with filling, and fry until golden brown.', 'Snack, Appetizer', 'https://cdn.pixabay.com/photo/2024/01/29/21/50/ai-generated-8540840_640.jpg'),
(1, 'Butter Chicken', 'A creamy and flavorful chicken curry made with a blend of aromatic spices, butter, and cream.', 'Chicken, Butter, Tomatoes, Cream, Ginger, Garlic, Garam Masala, Red Chili Powder, Kasuri Methi', 'Marinate chicken, cook in a spicy tomato gravy, and finish with butter and cream. Garnish with kasuri methi and serve with naan.', 'Main Course', 'https://www.shutterstock.com/image-photo/butter-chicken-murgh-makhani-juicy-600nw-2509416515.jpg'),
(1, 'Chole Bhature', 'A popular North Indian dish consisting of spicy chickpeas (chole) served with fried bread (bhature).', 'Chickpeas, Onion, Tomatoes, Garlic, Ginger, Garam Masala, Bhature Flour, Baking Powder, Yogurt', 'Cook chickpeas with spices, and serve with freshly fried bhature (bread).', 'Main Course', 'https://media.vogue.in/wp-content/uploads/2020/08/chole-bhature-recipe.jpg'),
(1, 'Pani Puri', 'A popular street food consisting of crispy puris filled with spiced water and chickpeas.', 'Semolina, Potatoes, Chickpeas, Tamarind, Cumin, Chaat Masala, Mint, Lemon Juice', 'Prepare the puris, fill with spiced water, potatoes, and chickpeas. Serve immediately with tamarind chutney.', 'Snack, Appetizer', 'https://i2.wp.com/wp-backend.thefearlesscooking.com/wp-content/uploads/2022/03/WhatsApp-Image-2022-03-10-at-4.45.10-PM.jpeg?fit=1536%2C1024&ssl=1'),
(1, 'Dosa', 'A thin, crispy pancake made from fermented rice and lentil batter, served with chutney and sambar.', 'Rice, Urad Dal (Black Gram), Fenugreek Seeds, Salt', 'Soak and grind rice and dal. Let the batter ferment overnight. Pour the batter on a hot griddle, cook until crispy, and serve with chutney and sambar.', 'Breakfast', 'https://images.pexels.com/photos/20422129/pexels-photo-20422129.jpeg?cs=srgb&dl=pexels-jack-baghel-2199968-20422129.jpg&fm=jpg'),
(1, 'Gulab Jamun', 'A popular Indian dessert made from milk solids, deep-fried and soaked in sugar syrup.', 'Milk Powder, Ghee, Flour, Baking Soda, Sugar, Water, Cardamom', 'Mix the ingredients to form a dough, shape into balls, deep-fry, and soak in warm sugar syrup flavored with cardamom.', 'Dessert', 'https://images.pexels.com/photos/15014919/pexels-photo-15014919.jpeg?cs=srgb&dl=pexels-nishess-shakya-401526881-15014919.jpg&fm=jpg');