INSERT INTO recipes (user_id, title, description, ingredients, instructions, category, image_url)
VALUES 
(1, 'Paneer Butter Masala', 'A rich, creamy curry made with paneer and a spiced tomato gravy.', 'Paneer, Butter, Tomatoes, Cream, Onion, Garlic, Ginger, Garam Masala, Kasuri Methi, Red Chili Powder', 'Sauté onions, garlic, and ginger in butter, add tomato puree and spices, cook until the gravy thickens. Add paneer cubes and simmer with cream. Garnish with kasuri methi and serve hot.', 'Main Course', 'https://myfoodstory.com/wp-content/uploads/2021/07/restaurant-style-paneer-butter-masala-2-500x500.jpg'),
(1, 'Chicken Biryani', 'A fragrant rice dish made with marinated chicken, aromatic spices, and basmati rice.', 'Chicken, Basmati Rice, Yogurt, Onion, Tomato, Garlic, Ginger, Garam Masala, Saffron, Ghee, Mint', 'Marinate chicken with yogurt and spices. Layer with partially cooked rice and cook on low heat (Dum) until the chicken is tender. Garnish with mint and fried onions.', 'Main Course', 'https://www.cubesnjuliennes.com/wp-content/uploads/2020/07/Chicken-Biryani-Recipe.jpg'),
(1, 'Aloo Gobi', 'A simple dry curry made with potatoes (Aloo) and cauliflower (Gobi).', 'Potatoes, Cauliflower, Onion, Tomatoes, Garlic, Ginger, Turmeric, Cumin, Coriander Powder, Garam Masala', 'Sauté onions, garlic, and ginger, then add potatoes and cauliflower along with spices. Cook until tender and serve with roti or rice.', 'Vegetarian', 'https://niksharmacooks.com/wp-content/uploads/2022/11/AlooGobiDSC_5234.jpg'),
(1, 'Masoor Dal', 'A hearty red lentil curry made with Indian spices.', 'Masoor Dal (Red Lentils), Onion, Tomatoes, Garlic, Ginger, Cumin Seeds, Turmeric, Coriander Powder, Garam Masala, Ghee', 'Cook lentils with turmeric until soft. Prepare a tadka with ghee, cumin, garlic, and spices. Add the tadka to the dal and simmer. Serve hot.', 'Vegan, Main Course', 'https://media.istockphoto.com/id/1130228942/photo/indian-dal-traditional-indian-soup-lentils-indian-dhal-spicy-curry-in-bowl-spices-herbs.jpg?s=612x612&w=0&k=20&c=ciPGZR4hkLeUL-nRxY4iAh539zYLgUkNz82GG_nJG5A='),
(1, 'Samosa', 'A crispy, deep-fried pastry filled with spiced potatoes and peas.', 'Potatoes, Green Peas, Onions, Ginger, Cumin Seeds, Garam Masala, Salt, Flour (for dough), Oil (for frying)', 'Prepare the filling by sautéing potatoes and peas with spices. Roll the dough, shape into triangles, stuff with filling, and fry until golden brown.', 'Snack, Appetizer', 'https://cdn.pixabay.com/photo/2024/01/29/21/50/ai-generated-8540840_640.jpg'),
(1, 'Butter Chicken', 'A creamy and flavorful chicken curry made with a blend of aromatic spices, butter, and cream.', 'Chicken, Butter, Tomatoes, Cream, Ginger, Garlic, Garam Masala, Red Chili Powder, Kasuri Methi', 'Marinate chicken, cook in a spicy tomato gravy, and finish with butter and cream. Garnish with kasuri methi and serve with naan.', 'Main Course', 'https://www.shutterstock.com/image-photo/butter-chicken-murgh-makhani-juicy-600nw-2509416515.jpg'),
(1, 'Chole Bhature', 'A popular North Indian dish consisting of spicy chickpeas (chole) served with fried bread (bhature).', 'Chickpeas, Onion, Tomatoes, Garlic, Ginger, Garam Masala, Bhature Flour, Baking Powder, Yogurt', 'Cook chickpeas with spices, and serve with freshly fried bhature (bread).', 'Main Course', 'https://media.vogue.in/wp-content/uploads/2020/08/chole-bhature-recipe.jpg'),
(1, 'Pani Puri', 'A popular street food consisting of crispy puris filled with spiced water and chickpeas.', 'Semolina, Potatoes, Chickpeas, Tamarind, Cumin, Chaat Masala, Mint, Lemon Juice', 'Prepare the puris, fill with spiced water, potatoes, and chickpeas. Serve immediately with tamarind chutney.', 'Snack, Appetizer', 'https://i2.wp.com/wp-backend.thefearlesscooking.com/wp-content/uploads/2022/03/WhatsApp-Image-2022-03-10-at-4.45.10-PM.jpeg?fit=1536%2C1024&ssl=1'),
(1, 'Dosa', 'A thin, crispy pancake made from fermented rice and lentil batter, served with chutney and sambar.', 'Rice, Urad Dal (Black Gram), Fenugreek Seeds, Salt', 'Soak and grind rice and dal. Let the batter ferment overnight. Pour the batter on a hot griddle, cook until crispy, and serve with chutney and sambar.', 'Breakfast', 'https://images.pexels.com/photos/20422129/pexels-photo-20422129.jpeg?cs=srgb&dl=pexels-jack-baghel-2199968-20422129.jpg&fm=jpg'),
(1, 'Gulab Jamun', 'A popular Indian dessert made from milk solids, deep-fried and soaked in sugar syrup.', 'Milk Powder, Ghee, Flour, Baking Soda, Sugar, Water, Cardamom', 'Mix the ingredients to form a dough, shape into balls, deep-fry, and soak in warm sugar syrup flavored with cardamom.', 'Dessert', 'https://images.pexels.com/photos/15014919/pexels-photo-15014919.jpeg?cs=srgb&dl=pexels-nishess-shakya-401526881-15014919.jpg&fm=jpg');
INSERT INTO recipes (user_id, title, description, ingredients, instructions, category, image_url)
VALUES 
(1, 'Rajma Chawal', 'A comforting dish of red kidney beans (rajma) cooked in a spiced tomato gravy, served with steamed rice.', 'Rajma (Kidney Beans), Onion, Tomato, Garlic, Ginger, Cumin, Turmeric, Garam Masala, Rice', 'Soak and boil rajma. Prepare a gravy with sautéed onions, garlic, ginger, and spices. Add boiled rajma and simmer. Serve with steamed rice.', 'Main Course', 'https://ranveerbrar.com/wp-content/uploads/2023/02/Kashmiri-rajma.jpg'),
(1, 'Rasgulla', 'A traditional Bengali dessert made with soft cheese balls soaked in sugar syrup.', 'Milk, Lemon Juice, Sugar, Water, Cardamom', 'Curdle milk to prepare chhena (paneer), knead it into soft balls, and cook in boiling sugar syrup. Serve chilled.', 'Dessert', 'https://cdn1.foodviva.com/static-content/food-images/desserts-sweets-recipes/rasgulla/rasgulla.jpg'),
(1, 'Idli', 'Steamed rice cakes made from fermented rice and lentil batter, served with sambar and coconut chutney.', 'Rice, Urad Dal, Fenugreek Seeds, Salt', 'Soak and grind rice and dal, let the batter ferment overnight, steam in molds, and serve with chutney and sambar.', 'Breakfast', 'https://www.foodie-trail.com/wp-content/uploads/2020/06/251fdbc0-57f6-41c3-a976-5192391cf040.jpg'),
(1, 'Rava Upma', 'A savory breakfast dish made from semolina (rava) cooked with spices and vegetables.', 'Semolina, Mustard Seeds, Curry Leaves, Green Chilies, Onion, Carrot, Peas, Ghee', 'Roast semolina, sauté spices and vegetables in ghee, add water, and mix in semolina. Cook until fluffy.', 'Breakfast', 'https://static.toiimg.com/thumb/84709540.cms?imgsize=221435&width=800&height=800'),
(1, 'Pav Bhaji', 'A famous street food consisting of spiced mashed vegetables served with buttered pav bread.', 'Potatoes, Peas, Carrots, Capsicum, Onion, Tomato, Garlic, Ginger, Pav Bhaji Masala, Butter, Pav Bread', 'Cook and mash vegetables, prepare a spiced gravy, mix in mashed vegetables, and serve with toasted pav.', 'Snack, Main Course', 'https://www.theculinarypeace.com/wp-content/uploads/2020/05/Pav-Bhaji.png'),
(1, 'Malai Kofta', 'A creamy curry featuring deep-fried paneer and potato balls served in a rich, spiced tomato gravy.', 'Paneer, Potatoes, Cream, Tomatoes, Onion, Garlic, Ginger, Cashews, Garam Masala', 'Prepare kofta by mixing paneer and potato, fry until golden. Make a creamy gravy with tomatoes, cashews, and cream. Add koftas and simmer.', 'Main Course', 'https://www.mrishtanna.com/wp-content/uploads/2023/11/vegan-malai-kofta-curry-500x500.jpg'),
(1, 'Vada Pav', 'A popular Mumbai street food featuring spicy potato fritters served in a bun.', 'Potatoes, Green Chilies, Ginger, Garlic, Besan (Chickpea Flour), Pav Bread, Tamarind Chutney, Green Chutney', 'Prepare spiced potato filling, coat with besan batter, and deep fry. Serve inside pav with chutneys.', 'Snack', 'https://www.cookwithmanali.com/wp-content/uploads/2018/04/Vada-Pav-500x375.jpg'),
(1, 'Bisi Bele Bath', 'A traditional Karnataka dish made with rice, lentils, vegetables, and a special spice blend.', 'Rice, Toor Dal, Tamarind, Vegetables, Bisi Bele Bath Powder, Curry Leaves, Mustard Seeds, Ghee', 'Cook rice and dal together. Prepare tamarind gravy with spices, add vegetables, and mix with rice-dal. Garnish with ghee and serve.', 'Main Course', 'https://www.karnatakatourism.org/wp-content/uploads/2020/05/bisi-bele-bhaat.jpg'),
(1, 'Mysore Pak', 'A rich South Indian dessert made with gram flour, sugar, and ghee.', 'Gram Flour, Sugar, Ghee', 'Roast gram flour in ghee, prepare a sugar syrup, and mix everything until thickened. Spread on a tray and cut into pieces.', 'Dessert', 'https://bansiwala.co.in/cdn/shop/files/MysorePak_01.jpg?v=1698482887&width=1445'),
(1, 'Palak Paneer', 'A creamy spinach curry with paneer cubes.', 'Spinach, Paneer, Onion, Garlic, Ginger, Tomatoes, Cream, Cumin, Garam Masala', 'Blanch spinach, blend into a puree, and cook with spices and cream. Add paneer cubes and serve hot.', 'Main Course', 'https://cdn.zeptonow.com/production///tr:w-600,ar-100-100,pr-true,f-auto,q-80/web/recipes/palak-paneer.png');

INSERT INTO recipes (user_id, title, description, ingredients, instructions, category, image_url)
VALUES 
(1, 'Fish Curry', 'A spicy and tangy curry made with fish and traditional Indian spices.', 'Fish, Tamarind, Coconut Milk, Curry Leaves, Mustard Seeds, Onion, Garlic, Ginger, Turmeric, Red Chili Powder', 'Marinate fish with turmeric and salt. Prepare a spiced gravy with tamarind and coconut milk. Add fish and simmer until cooked.', 'Main Course', 'https://img.freepik.com/premium-photo/fish-curry-seer-fish-curry-traditional-indian-fish-curry-kerala-special-dish-using-coconut-arranged-white-bowl-garnished-with-curry-leaves-malabar-tamarind-white-textured-background_527904-2016.jpg?semt=ais_hybrid'),
(1, 'Keema Matar', 'A minced meat curry cooked with green peas and spices.', 'Minced Meat (Keema), Green Peas, Onion, Garlic, Ginger, Tomato, Garam Masala, Cumin, Turmeric', 'Sauté onions, garlic, and ginger. Add minced meat, tomatoes, and spices. Cook until tender, then mix in green peas. Garnish with coriander and serve hot.', 'Main Course', 'https://j6e2i8c9.rocketcdn.me/wp-content/uploads/2014/11/Chicken-keema-matar-11.jpg'),
(1, 'Prawns Masala', 'A delicious spicy prawn curry made with a blend of aromatic spices and coconut.', 'Prawns, Coconut Milk, Onion, Garlic, Ginger, Curry Leaves, Mustard Seeds, Turmeric, Red Chili Powder', 'Marinate prawns with turmeric and salt. Prepare a coconut-based spiced curry and cook prawns until tender. Serve hot.', 'Main Course', 'https://www.licious.in/blog/wp-content/uploads/2020/12/Prawns-Masala-min.jpg'),
(1, 'Chicken Tikka', 'Spiced, marinated chicken pieces grilled to perfection.', 'Chicken, Yogurt, Garlic, Ginger, Red Chili Powder, Garam Masala, Lemon Juice, Mustard Oil', 'Marinate chicken in spiced yogurt mixture. Grill or bake until charred and cooked through. Serve with mint chutney.', 'Appetizer', 'https://www.shutterstock.com/image-photo/deliciously-spiced-chicken-tikka-kabab-600nw-2495838045.jpg'),
(1, 'Egg Curry', 'A simple and hearty curry made with boiled eggs in a spiced tomato gravy.', 'Eggs, Onion, Tomatoes, Garlic, Ginger, Turmeric, Red Chili Powder, Garam Masala, Cumin', 'Boil and peel eggs. Prepare a spiced tomato-onion gravy, add eggs, and simmer for a few minutes. Serve hot with rice or roti.', 'Main Course', 'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/04/egg-curry-recipe.jpg'),
(1, 'Chicken Korma', 'A creamy and mildly spiced chicken curry with yogurt and cashews.', 'Chicken, Yogurt, Cashews, Onion, Garlic, Ginger, Garam Masala, Turmeric, Cream', 'Marinate chicken with yogurt and spices. Cook in a rich gravy made with cashews and onions. Simmer with cream for a smooth finish.', 'Main Course', 'https://www.shutterstock.com/image-photo/chicken-curry-masalakerala-style-using-600nw-1903754347.jpg'),
(1, 'Tandoori Chicken', 'A classic Indian dish of chicken marinated in yogurt and spices, cooked in a tandoor or oven.', 'Chicken, Yogurt, Lemon Juice, Garlic, Ginger, Red Chili Powder, Garam Masala, Mustard Oil', 'Marinate chicken with spiced yogurt mixture and cook in a tandoor or oven until charred and tender.', 'Appetizer', 'https://onestophalal.com/cdn/shop/articles/air_fryer_chicken_tandoori-1694242200588_1200x.jpg?v=1694242335'),
(1, 'Goan Fish Curry', 'A tangy and spicy curry made with fish and coconut milk, flavored with Goan spices.', 'Fish, Coconut Milk, Tamarind, Curry Leaves, Mustard Seeds, Red Chilies, Turmeric, Garlic, Ginger', 'Prepare a coconut-based spiced curry. Add tamarind and fish, simmer until cooked. Serve with rice.', 'Main Course', 'https://static.toiimg.com/thumb/55224612.cms?width=1200&height=900'),
(1, 'Chicken 65', 'A spicy and crispy fried chicken dish popular in South India.', 'Chicken, Yogurt, Curry Leaves, Garlic, Ginger, Red Chili Powder, Cornflour, Lemon Juice', 'Marinate chicken with spices and yogurt. Deep-fry until crispy. Toss with curry leaves and red chili sauce for extra flavor.', 'Snack, Appetizer', 'https://bonmasala.com/wp-content/uploads/2022/06/Chicken-65-recipe.webp');
INSERT INTO recipes (user_id, title, description, ingredients, instructions, category, image_url)
VALUES 
(1, 'Tandoori Roti', 'A soft, fluffy bread cooked in a tandoor, perfect with Indian curries.', 'Whole Wheat Flour, Yogurt, Salt, Baking Soda, Water', 'Mix flour, yogurt, salt, and baking soda to form a soft dough. Roll into rounds and cook in a hot tandoor or oven.', 'Bread', 'https://sinfullyspicy.com/wp-content/uploads/2024/05/1200-by-1200-images.jpg'),
(1, 'Tawa Roti', 'A staple Indian flatbread made on a tawa (griddle).', 'Whole Wheat Flour, Water, Salt', 'Knead flour and water into a dough. Roll into thin rounds and cook on a hot tawa until golden brown spots appear.', 'Bread', 'https://thewoods.net.in/wp-content/uploads/2021/02/veg11.jpg'),
(1, 'Naan', 'A leavened flatbread cooked in a tandoor, often served with butter or garlic.', 'All-Purpose Flour, Yogurt, Yeast, Sugar, Salt, Butter (optional)', 'Prepare a soft dough with flour, yeast, yogurt, and salt. Let it rise, roll into ovals, and cook in a tandoor or oven.', 'Bread', 'https://img.freepik.com/free-photo/top-view-pakistani-meal-arrangement_23-2148825100.jpg'),
(1, 'Butter Naan', 'A rich, soft naan brushed with melted butter for added flavor.', 'All-Purpose Flour, Yogurt, Yeast, Sugar, Salt, Butter', 'Make naan dough with flour, yeast, and yogurt. Cook in a tandoor or oven and brush with melted butter before serving.', 'Bread', 'https://media.istockphoto.com/id/1143530040/photo/indian-naan-bread-with-garlic-butter-on-wooden-table.jpg?s=612x612&w=0&k=20&c=71SgbJtnfiHUiud1oGxnhiZsx5nuivWwZt8DlIk8hi0='),
(1, 'Garlic Naan', 'A flavorful naan topped with minced garlic and cilantro.', 'All-Purpose Flour, Yogurt, Yeast, Garlic, Cilantro, Butter, Salt', 'Prepare naan dough and roll into ovals. Add minced garlic and cilantro on top, cook in a tandoor or oven, and brush with butter.', 'Bread', 'https://img.freepik.com/free-photo/pakistani-food-wooden-board-top-view_23-2148825093.jpg'),
(1, 'Laccha Paratha', 'A layered, crispy flatbread made with whole wheat flour.', 'Whole Wheat Flour, Salt, Ghee, Water', 'Roll dough into a thin circle, spread ghee, fold into layers, and roll again. Cook on a hot tawa until golden and crispy.', 'Bread', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOFBytmultfdbFium2PSR7mRx_N-MRUE73Rw&s'),
(1, 'Missi Roti', 'A spiced flatbread made with a mix of gram flour and whole wheat flour.', 'Gram Flour (Besan), Whole Wheat Flour, Cumin Seeds, Onion, Green Chilies, Salt', 'Knead a dough with flours, spices, and water. Roll into rounds and cook on a hot tawa.', 'Bread', 'https://static.toiimg.com/thumb/54504896.cms?width=1200&height=900'),
(1, 'Kulcha', 'A soft, leavened bread traditionally cooked in a tandoor.', 'All-Purpose Flour, Yogurt, Baking Powder, Baking Soda, Salt, Butter', 'Mix flour with yogurt and leavening agents to form a dough. Roll and cook in a tandoor or oven. Brush with butter before serving.', 'Bread', 'https://static.toiimg.com/photo/62376759.cms'),